app = "lucky-compass-backend"
primary_region = "ord"
[build]
  dockerfile = "Dockerfile"
[env]
  PORT = "8080"
  HTTP_PROXY = ""
  HTTPS_PROXY = ""
  PIP_INDEX_URL = "https://mirrors.aliyun.com/pypi/simple/"
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/calculate?year=1984&month=5&day=10"