app = "lucky-compass-backend"
primary_region = "ord"

[build]
  builder = "heroku/builder:24"
  buildpacks = ["heroku/python"]

[env]
  PORT = "8080"
  HTTP_PROXY = ""
  HTTPS_PROXY = ""
  PIP_INDEX_URL = "https://mirrors.huaweicloud.com/pypi/simple/"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0