app = "lucky-compass-backend"
primary_region = "ord"
[build]
  dockerfile = "Dockerfile"
[env]
  PORT = "8080"
  HTTP_PROXY = ""
  HTTPS_PROXY = ""
  PIP_INDEX_URL = "https://mirrors.aliyun.com/pypi/simple/"
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1