app = "lucky-compass-backend"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  HTTP_PROXY = ""
  HTTPS_PROXY = ""
  PIP_INDEX_URL = "https://mirrors.aliyun.com/pypi/simple/"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  [[http_service.checks]]
    interval = "15s"
    timeout = "2s"  # 缩短超时，/health 响应更快
    grace_period = "10s"
    method = "GET"
    path = "/health"

[processes]
  app = "gunicorn --bind :8080 --workers 2 --log-level debug app:app"